kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
provisioner: ceph.com/cephfs
parameters:
  monitors: 192.168.7.53:6789,192.168.7.54:6789,192.168.7.55:6789
  adminId: admin
  adminSecretName: ceph-admin
  adminSecretNamespace: kube-system
  claimRoot: /volumes/kubernetes
